@HOST = http://192.168.70.3:18080

### 插入一条数据
POST {{HOST}}/mongodb/test-collection
Content-Type: application/json

< ./test.json

### 删除一条数据
DELETE {{HOST}}/mongodb/test-collection/code-1


### 更新一条数据-update指令
PUT {{HOST}}/mongodb/test-collection/code-1/update
Content-Type: application/json

{
  "name":"name-update"
}

### 更新一条数据-findAndModify指令
PUT {{HOST}}/mongodb/test-collection/code-1/findAndModify
Content-Type: application/json

{
  "name":"name-findAndModify-2"
}

### 读取一条数据
GET {{HOST}}/mongodb/test-collection/code-1


### 更新一条数据-脏读验证接口
PUT {{HOST}}/mongodb/test-collection/code-1/dirty-read

### 读取脏读日志
GET {{HOST}}/mongodb/dirty-read-log

### 清理脏读日志
DELETE {{HOST}}/mongodb/dirty-read-log